[package]
name = "timecode"
version = "0.1.0"
authors = ["John Schmidt <john@john2143.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum_dispatch = "0.3.7"
nom = "7.0.0"
#smallstr = "0.2.0"

[dev-dependencies]
smallstr = "0.2.0"
