[package]
name = "timecode"
version = "0.1.0"
authors = ["John Schmidt <john@john2143.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default=[]
javascript=["wasm-bindgen"]
python=["pyo3"]

[lib]
name = "timecode"
crate-type = ["cdylib", "rlib"]

[dependencies]
nom = "7.0.0"
pyo3 = { version = "0.17.1", features = ["extension-module"], optional = true }
wasm-bindgen = { version = "0.2.82", optional = true }
#smallstr = "0.2.0"

[dev-dependencies]
smallstr = "0.2.0"
