class Timecode:
    def __init__(self, timecode_or_number_of_frames: str, framerate: str) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def ts(self) -> str: ...
    def add(self, tc: Timecode) -> Timecode: ...
    def add_frames(self, frames: int) -> Timecode: ...
    def sub_frames(self, frames: int) -> Timecode: ...
    def frame_count(self) -> int: ...
    def convert_to(self, framerate: str) -> Timecode: ...
    def convert_with_start(self, framerate: str, start: Timecode) -> Timecode: ...
    def framerate(self) -> float: ...
    def is_dropframe(self) -> bool: ...
