name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Packages
      uses: actions/cache@v3
      id: cache-packages
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargodeps-${{ hashFiles('**/Cargo.toml') }}

    - name: install rust deps
      if: steps.cache-packages.outputs.cache-hit != 'true'
      run: cargo install wasm-pack cargo-llvm-cov cargo-fuzz

    - name: install maturin
      run: pip3 install maturin

    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose --release

    - name: Build for JS
      run: make node
    - name: Build for python
      run: make python

    - name: Build
      run: echo ${{ github.sha }} > Release.txt

    - name: Make release
      if: github.ref == 'refs/heads/master'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: rel${{ github.sha }}
        release_name: Release ${{ github.job }}
        draft: false
        prerelease: false

    - name: Upload JS Assets
      if: github.ref == 'refs/heads/master'
      id: upload-release-asset-js
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: timecode_js_node.zip
        asset_name: timecode_js_node.zip
        asset_content_type: application/zip
    - name: Upload JS Web Assets
      if: github.ref == 'refs/heads/master'
      id: upload-release-asset-js-web
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: timecode_js_web.zip
        asset_name: timecode_js_web.zip
        asset_content_type: application/zip
    - name: Upload python Assets
      if: github.ref == 'refs/heads/master'
      id: upload-release-asset-py
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/wheels/timecode-0.1.0-cp38-cp38-manylinux_2_28_x86_64.whl
        asset_name: timecode.whl
        asset_content_type: application/binary
    - name: Upload release.txt
      if: github.ref == 'refs/heads/master'
      id: upload-release-asset-txt
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Release.txt
        asset_name: Release.txt
        asset_content_type: application/txt
    #- name: Fuzz
      #run: cargo fuzz run fuzz_target_1
