name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: install wasm-pack
      run: cargo install wasm-pack
    - name: Build for JS
      run: make node
    - name: install maturin
      run: pip3 install maturin
    - name: Build for python
      run: make python
