name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Packages
      uses: actions/cache@v3
      id: cache-packages
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargodeps-${{ hashFiles('**/Cargo.toml') }}

    - name: install rust deps
      if: steps.cache-packages.outputs.cache-hit != 'true'
      run: cargo install wasm-pack cargo-llvm-cov cargo-fuzz

    - name: install maturin
      run: pip3 install maturin

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

    - name: Build for JS
      run: make node
    - name: Build for python
      run: make python

    #- name: Fuzz
      #run: cargo fuzz run fuzz_target_1
